// India H2 Workforce Atlas — D3.js Treemap
// Generated by build.py — do not edit directly. Edit main.js.template instead.
// /india-h2-jobs is replaced by build.py with the correct path prefix.

(function () {
  "use strict";

  const BASE_URL = "/india-h2-jobs";
  const DIMENSIONS = [
    { key: "h2_adjacency", label: "H2 Adjacency" },
    { key: "transition_demand", label: "Transition Demand" },
    { key: "skill_transferability", label: "Skill Transfer" },
    { key: "digital_automation_exposure", label: "AI Exposure" },
    { key: "formalization_rate", label: "Formalization" },
    { key: "scarcity_risk", label: "Scarcity Risk" },
  ];

  const COLOUR_BANDS = [
    { min: 9, max: 10, colour: "#00994C", label: "Core H2" },      // HyGOAT green
    { min: 7, max: 8.99, colour: "#50C878", label: "Strong" },      // Emerald
    { min: 5, max: 6.99, colour: "#86efac", label: "Adjacent" },    // Light green
    { min: 3, max: 4.99, colour: "#ff8a00", label: "Transferable" },// HyGOAT orange
    { min: 1, max: 2.99, colour: "#dc2626", label: "Low relevance" },
  ];
  const NULL_COLOUR = "#374151";

  let data = null;
  let activeDimension = "h2_adjacency";
  let selectedOccupation = null;

  // --- Data Loading ---

  async function loadData() {
    const url = BASE_URL ? `${BASE_URL}/occupations.json` : "occupations.json";
    const resp = await fetch(url);
    if (!resp.ok) throw new Error(`Failed to load data: ${resp.status}`);
    data = await resp.json();
    return data;
  }

  // --- Colour ---

  function scoreColour(score) {
    if (score == null) return NULL_COLOUR;
    for (const band of COLOUR_BANDS) {
      if (score >= band.min && score <= band.max) return band.colour;
    }
    if (score > 0 && score < 1) return "#dc2626";
    return NULL_COLOUR;
  }

  // --- Summary Bar ---

  function updateSummary() {
    if (!data || !data.summary) return;
    const s = data.summary;
    document.getElementById("metricH2Ready").textContent = s.h2_ready_occupations.toLocaleString();
    document.getElementById("metricGap").textContent = (s.workforce_gap_2030 / 1e6).toFixed(1) + "M";
    document.getElementById("metricUpskill").textContent = s.fast_upskill_paths.toLocaleString();

    // Footer
    document.getElementById("footerVersion").textContent = `Dataset v${data.dataset_version}`;
    const d = new Date(data.last_updated);
    document.getElementById("footerDate").textContent = `Last updated ${d.toLocaleDateString("en-US", { month: "long", year: "numeric" })}`;
  }

  // --- Treemap ---

  function buildTreemap() {
    const container = document.getElementById("treemap");
    container.innerHTML = "";

    const width = container.clientWidth;
    const height = container.clientHeight || 500;

    // Build hierarchy: root -> sectors -> occupations
    const sectors = {};
    for (const occ of data.occupations) {
      const s = occ.sector || "Other";
      if (!sectors[s]) sectors[s] = { name: s, children: [] };
      sectors[s].children.push(occ);
    }

    const hierarchy = {
      name: "root",
      children: Object.values(sectors),
    };

    const root = d3.hierarchy(hierarchy)
      .sum(d => {
        // Leaf nodes: use employment or 1 as fallback
        if (d.id) return d.employment || 1;
        return 0;
      })
      .sort((a, b) => (b.value || 0) - (a.value || 0));

    d3.treemap()
      .size([width, height])
      .padding(1)
      .paddingTop(14)
      .round(true)(root);

    const svg = d3.select(container)
      .append("svg")
      .attr("width", width)
      .attr("height", height);

    // Sector labels
    const sectorNodes = root.children || [];
    svg.selectAll(".sector-label")
      .data(sectorNodes)
      .join("text")
      .attr("class", "sector-label")
      .attr("x", d => d.x0 + 3)
      .attr("y", d => d.y0 + 11)
      .text(d => d.data.name)
      .attr("font-size", "10px")
      .attr("font-weight", "600")
      .attr("fill", "#64748b")
      .each(function (d) {
        const availWidth = d.x1 - d.x0 - 6;
        if (this.getComputedTextLength() > availWidth) {
          this.textContent = "";
        }
      });

    // Leaf cells (occupations)
    const leaves = root.leaves();

    const cells = svg.selectAll(".cell")
      .data(leaves)
      .join("g")
      .attr("class", "cell")
      .attr("transform", d => `translate(${d.x0},${d.y0})`);

    cells.append("rect")
      .attr("width", d => Math.max(0, d.x1 - d.x0))
      .attr("height", d => Math.max(0, d.y1 - d.y0))
      .attr("fill", d => {
        const scores = d.data.scores || {};
        return scoreColour(scores[activeDimension]);
      })
      .attr("data-id", d => d.data.id)
      .on("mouseover", onCellHover)
      .on("mousemove", onCellMove)
      .on("mouseout", onCellOut)
      .on("click", (event, d) => selectOccupation(d.data));

    // Text labels (only if cell is wide enough)
    cells.append("text")
      .attr("class", "cell-label")
      .attr("x", 3)
      .attr("y", 12)
      .text(d => d.data.title)
      .each(function (d) {
        const cellWidth = d.x1 - d.x0;
        if (cellWidth < 40) {
          this.textContent = "";
          return;
        }
        // Truncate
        const maxChars = Math.floor(cellWidth / 6);
        if (this.textContent.length > maxChars) {
          this.textContent = this.textContent.slice(0, maxChars - 1) + "\u2026";
        }
      });
  }

  // --- Tooltip ---

  function onCellHover(event, d) {
    const tooltip = document.getElementById("tooltip");
    const scores = d.data.scores || {};
    const score = scores[activeDimension];
    const scoreText = score != null ? score.toFixed(1) : "N/A";
    const dimLabel = DIMENSIONS.find(dim => dim.key === activeDimension)?.label || activeDimension;
    tooltip.innerHTML = `<strong>${d.data.title}</strong><br>${dimLabel}: ${scoreText}`;
    tooltip.style.display = "block";
  }

  function onCellMove(event) {
    const tooltip = document.getElementById("tooltip");
    const container = document.getElementById("treemapContainer");
    const rect = container.getBoundingClientRect();
    tooltip.style.left = (event.clientX - rect.left + 12) + "px";
    tooltip.style.top = (event.clientY - rect.top - 10) + "px";
  }

  function onCellOut() {
    document.getElementById("tooltip").style.display = "none";
  }

  // --- Sidebar ---

  function selectOccupation(occ) {
    selectedOccupation = occ;
    document.querySelector(".sidebar-empty").style.display = "none";
    document.getElementById("sidebarContent").style.display = "block";

    document.getElementById("sbTitle").textContent = occ.title;
    document.getElementById("sbSector").textContent = occ.sector;
    document.getElementById("sbNco").textContent = occ.nco_code || "";
    document.getElementById("sbEdu").textContent = occ.education_req || "";

    document.getElementById("sbEmployment").textContent = occ.employment
      ? occ.employment.toLocaleString()
      : "N/A";
    document.getElementById("sbWage").textContent = occ.median_wage_inr
      ? "\u20B9" + occ.median_wage_inr.toLocaleString()
      : "N/A";

    // Score bars
    const barsEl = document.getElementById("scoreBars");
    barsEl.innerHTML = "";
    for (const dim of DIMENSIONS) {
      const score = (occ.scores || {})[dim.key];
      const pct = score != null ? (score / 10) * 100 : 0;
      const colour = scoreColour(score);
      barsEl.innerHTML += `
        <div class="score-bar-row">
          <span class="score-bar-label">${dim.label}</span>
          <div class="score-bar-track">
            <div class="score-bar-fill" style="width:${pct}%;background:${colour}"></div>
          </div>
          <span class="score-bar-value">${score != null ? score.toFixed(1) : "N/A"}</span>
        </div>`;
    }

    // Upskill paths
    const listEl = document.getElementById("upskillList");
    listEl.innerHTML = "";
    const paths = occ.upskill_paths || [];
    if (paths.length === 0) {
      listEl.innerHTML = '<div style="color:#64748b;font-size:0.85rem">No upskill paths available</div>';
    }
    for (const targetId of paths) {
      const target = data.occupations.find(o => o.id === targetId);
      if (!target) continue;
      const h2 = (target.scores || {}).h2_adjacency || 0;
      const td = (target.scores || {}).transition_demand || 0;
      const combined = (h2 + td).toFixed(1);
      const item = document.createElement("div");
      item.className = "upskill-item";
      item.innerHTML = `<span>${target.title}</span><span class="upskill-score">${combined}</span>`;
      item.addEventListener("click", () => highlightCell(targetId));
      listEl.appendChild(item);
    }
  }

  function highlightCell(targetId) {
    // Remove previous highlights
    d3.selectAll(".highlight-cell").classed("highlight-cell", false);

    const rect = d3.select(`rect[data-id="${targetId}"]`);
    if (!rect.empty()) {
      rect.classed("highlight-cell", true);
      // Scroll into view
      const node = rect.node();
      if (node) node.scrollIntoView({ behavior: "smooth", block: "center" });
    }
  }

  // --- Colour Toggle ---

  function setupDimensionPills() {
    document.querySelectorAll(".pill").forEach(pill => {
      pill.addEventListener("click", () => {
        document.querySelectorAll(".pill").forEach(p => p.classList.remove("active"));
        pill.classList.add("active");
        activeDimension = pill.dataset.dim;
        recolourTreemap();
      });
    });
  }

  function recolourTreemap() {
    d3.selectAll("#treemap rect[data-id]").attr("fill", function () {
      const id = this.getAttribute("data-id");
      const occ = data.occupations.find(o => o.id === id);
      if (!occ) return NULL_COLOUR;
      return scoreColour((occ.scores || {})[activeDimension]);
    });
  }

  // --- CSV Download ---

  function setupDownloads() {
    const btn = document.getElementById("downloadBtn");
    const menu = document.getElementById("downloadMenu");

    btn.addEventListener("click", (e) => {
      e.stopPropagation();
      menu.classList.toggle("open");
    });
    document.addEventListener("click", () => menu.classList.remove("open"));

    document.getElementById("dlFull").addEventListener("click", (e) => {
      e.preventDefault();
      downloadCSV(data.occupations, "occupations.csv");
    });

    document.getElementById("dlH2").addEventListener("click", (e) => {
      e.preventDefault();
      const h2 = data.occupations.filter(o => (o.scores || {}).h2_adjacency >= 7);
      downloadCSV(h2, "h2-ready-occupations.csv");
    });
  }

  function downloadCSV(occupations, filename) {
    const headers = ["id", "slug", "title", "sector", "nco_code", "employment", "median_wage_inr",
      "education_req", "formal_sector_pct", "h2_adjacency", "transition_demand",
      "skill_transferability", "digital_automation_exposure", "formalization_rate", "scarcity_risk"];

    const rows = [headers.join(",")];
    for (const occ of occupations) {
      const vals = headers.map(h => {
        if (h in (occ.scores || {})) return occ.scores[h] ?? "";
        const v = occ[h];
        if (v == null) return "";
        if (typeof v === "string" && v.includes(",")) return `"${v}"`;
        return v;
      });
      rows.push(vals.join(","));
    }

    const blob = new Blob([rows.join("\n")], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  }

  // --- Init ---

  async function init() {
    try {
      await loadData();
      updateSummary();
      buildTreemap();
      setupDimensionPills();
      setupDownloads();

      // Rebuild on resize
      let resizeTimer;
      window.addEventListener("resize", () => {
        clearTimeout(resizeTimer);
        resizeTimer = setTimeout(buildTreemap, 250);
      });
    } catch (err) {
      console.error("Atlas init error:", err);
      document.getElementById("treemap").innerHTML =
        `<div style="padding:2rem;color:#dc2626">Failed to load data. ${err.message}</div>`;
    }
  }

  init();
})();
